//! Build-time-baked content hashes of this build's bundled providers.
//!
//! Generated by `build.rs` from the `MFR_BUNDLED_PROVIDER_HASHES` env var (a
//! JSON `{name: {version: sha256}}` map the build pipeline computes after
//! building the provider binaries, before compiling this crate's consumers).
//! Empty when no providers were bundled. See the build script's
//! `generate_bundled_provider_hashes` doc for the contract.
//!
//! `cartridge_discovery` verifies any cartridge marked `installed_from: bundle`
//! against this set: a bundled provider whose on-disk directory does not hash to
//! its baked value (or is absent from the set) is surfaced incompatible and
//! never hosted.

include!(concat!(env!("OUT_DIR"), "/bundled_provider_hashes.rs"));
